import { create } from "zustand";
import { persist } from "zustand/middleware";
import { demoUsers, managers, venues } from "../data/seed";
import type { Booking, EventRequirement, ManagerRequest, Message, Notification, Proposal, Review, User, VenueInquiry } from "../types";

const uid=(p:string)=>`${p}-${Date.now()}`;
const notification=(userId:string,title:string,message:string):Notification=>({id:uid("note"),userId,title,message,type:"info",read:false,createdAt:new Date().toISOString()});
type Store={user:User|null;users:User[];events:EventRequirement[];managers:typeof managers;venues:typeof venues;requests:ManagerRequest[];inquiries:VenueInquiry[];proposals:Proposal[];bookings:Booking[];messages:Message[];notifications:Notification[];reviews:Review[];login:(e:string,p:string)=>{ok:boolean;message?:string};signup:(u:Omit<User,"id">)=>void;logout:()=>void;reset:()=>void;createEvent:(e:Omit<EventRequirement,"id"|"customerId"|"status">)=>string;sendRequest:(e:string,m:string)=>void;acceptRequest:(r:string,a:boolean)=>void;sendInquiry:(e:string,v:string,msg:string)=>void;respondInquiry:(i:string,a:boolean,q?:number)=>void;createProposal:(e:string,v:string,items:Proposal["items"],d:string)=>void;decideProposal:(p:string,d:"accepted"|"rejected"|"changes_requested",msg?:string)=>void;pay:(b:string)=>void;sendMessage:(to:string,text:string)=>void;markRead:(id:string)=>void;submitReview:(b:string,t:string,r:number,c:string)=>void};
const initial={user:null,users:demoUsers,events:[],managers,venues,requests:[],inquiries:[],proposals:[],bookings:[],messages:[],notifications:[],reviews:[]};
export const useStore=create<Store>()(persist((set,get)=>({...initial,
 login:(email,password)=>{const user=get().users.find(u=>u.email.toLowerCase()===email.toLowerCase());if(!user||password!=="Demo@123")return{ok:false,message:"Use a demo account and password Demo@123."};set({user});return{ok:true}},
 signup:u=>set(s=>({users:[...s.users,{...u,id:uid("user"),approved:u.role==="customer"}],user:{...u,id:uid("session"),approved:u.role==="customer"}})),logout:()=>set({user:null}),reset:()=>set(initial),
 createEvent:e=>{const event={...e,id:uid("EVT"),customerId:get().user!.id,status:"draft" as const};set(s=>({events:[...s.events,event]}));return event.id},
 sendRequest:(eventId,managerId)=>{const event=get().events.find(e=>e.id===eventId)!;const request={id:uid("REQ"),eventId,customerId:event.customerId,managerId,status:"pending" as const,createdAt:new Date().toISOString()};set(s=>({requests:[...s.requests,request],events:s.events.map(e=>e.id===eventId?{...e,status:"requested"}:e),notifications:[...s.notifications,notification(managerId,"New event request",`${event.eventName} needs your help.`)]}))},
 acceptRequest:(requestId,accepted)=>{const request=get().requests.find(r=>r.id===requestId)!;set(s=>({requests:s.requests.map(r=>r.id===requestId?{...r,status:accepted?"accepted":"rejected"}:r),events:s.events.map(e=>e.id===request.eventId?{...e,status:accepted?"in_progress":"draft"}:e),notifications:[...s.notifications,notification(request.customerId,accepted?"Manager accepted":"Request declined",accepted?"Your event manager is now finding venues.":"Choose another event manager.")]}))},
 sendInquiry:(eventId,venueId,message)=>{const user=get().user!;const venue=get().venues.find(v=>v.id===venueId)!;const inquiry={id:uid("INQ"),eventId,managerId:user.id,venueId,status:"pending" as const,message,createdAt:new Date().toISOString()};set(s=>({inquiries:[...s.inquiries,inquiry],notifications:[...s.notifications,notification(venue.managerId,"New venue inquiry","An event manager has requested availability.")]}))},
 respondInquiry:(inquiryId,accepted,quote)=>{const inquiry=get().inquiries.find(i=>i.id===inquiryId)!;set(s=>({inquiries:s.inquiries.map(i=>i.id===inquiryId?{...i,status:accepted?"quoted":"rejected",quote}:i),notifications:[...s.notifications,notification(inquiry.managerId,accepted?"Venue quotation received":"Venue inquiry declined",accepted?`Quote received: ₹${quote?.toLocaleString("en-IN")}`:"Please try another venue.")]}))},
 createProposal:(eventId,venueId,items,description)=>{const event=get().events.find(e=>e.id===eventId)!;const request=get().requests.find(r=>r.eventId===eventId&&r.status==="accepted")!;const proposal:Proposal={id:uid("PROP"),eventId,customerId:event.customerId,managerId:request.managerId,venueId,title:`${event.eventName} proposal`,description,items,totalAmount:items.reduce((a,i)=>a+i.price*i.quantity,0),status:"sent",expiry:"2026-12-31",createdAt:new Date().toISOString()};set(s=>({proposals:[...s.proposals,proposal],events:s.events.map(e=>e.id===eventId?{...e,status:"proposal_sent"}:e),notifications:[...s.notifications,notification(event.customerId,"Your proposal is ready",`Review the proposal for ${event.eventName}.`)]}))},
 decideProposal:(proposalId,decision,message)=>{const proposal=get().proposals.find(p=>p.id===proposalId)!;if(decision==="accepted"){const booking:Booking={id:uid("BK"),eventId:proposal.eventId,customerId:proposal.customerId,managerId:proposal.managerId,venueId:proposal.venueId,proposalId:proposal.id,amount:proposal.totalAmount,deposit:Math.round(proposal.totalAmount*.25),paymentStatus:"pending",bookingStatus:"pending",createdAt:new Date().toISOString()};set(s=>({proposals:s.proposals.map(p=>p.id===proposalId?{...p,status:decision}:p),bookings:[...s.bookings,booking],notifications:[...s.notifications,notification(proposal.managerId,"Proposal accepted","Customer accepted your proposal."),notification(proposal.customerId,"Continue to payment","Your booking deposit is ready to pay.")]}))}else set(s=>({proposals:s.proposals.map(p=>p.id===proposalId?{...p,status:decision}:p),notifications:[...s.notifications,notification(proposal.managerId,decision==="changes_requested"?"Changes requested":"Proposal rejected",message||"Please review the customer response.")]}))},
 pay:bookingId=>{const booking=get().bookings.find(b=>b.id===bookingId)!;const venue=get().venues.find(v=>v.id===booking.venueId)!;set(s=>({bookings:s.bookings.map(b=>b.id===bookingId?{...b,paymentStatus:"paid",bookingStatus:"confirmed"}:b),events:s.events.map(e=>e.id===booking.eventId?{...e,status:"confirmed"}:e),notifications:[...s.notifications,notification(booking.customerId,"Booking confirmed",`Deposit of ₹${booking.deposit.toLocaleString("en-IN")} received.`),notification(booking.managerId,"Booking confirmed","Your customer has paid the deposit."),notification(venue.managerId,"Booking confirmed","A new confirmed booking is on your calendar.")]}))},
 sendMessage:(receiverId,text)=>{const sender=get().user!;const message:Message={id:uid("MSG"),senderId:sender.id,receiverId,text,read:false,createdAt:new Date().toISOString()};set(s=>({messages:[...s.messages,message],notifications:[...s.notifications,notification(receiverId,"New message",`${sender.name}: ${text.slice(0,45)}`)]}))},markRead:id=>set(s=>({notifications:s.notifications.map(n=>n.id===id?{...n,read:true}:n)})),submitReview:(bookingId,targetId,rating,comment)=>{const user=get().user!;set(s=>({reviews:[...s.reviews,{id:uid("REV"),bookingId,targetId,customerId:user.id,rating,comment,createdAt:new Date().toISOString()}]}))}
}),{name:"eventmithra-demo-v2"}));
